ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.WebsocketsKt.configureWebsockets
      - com.example.RoutingKt.configureRouting
