# sytleguide
kotlin.code.style = official
# mpp
kotlin.native.binary.memoryModel = experimental
# gradle configuration
org.gradle.configureondemand = false
kotlin.mpp.applyDefaultHierarchyTemplate=false
org.gradle.java.installations.auto-download=false
# versions
ktor_version = 3.6.0
org.gradle.jvmargs = -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
