pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("com.google.cloud.tools.appengine")) {
                useModule("com.google.cloud.tools:appengine-gradle-plugin:${requested.version}")
            }
        }
    }
}

rootProject.name = "ktor-codesnippets"

fun module(group: String, name: String) {
    include(name)
    project(":$name").projectDir = file("$group/$name")
}

// ---------------------------

module("snippets", "jetty-war")
module("snippets", "tomcat-war")
module("snippets", "docker")
module("snippets", "auth-basic")
module("snippets", "auth-basic-hash-table")
module("snippets", "auth-digest")
module("snippets", "auth-form")
module("snippets", "auth-form-html-dsl")
module("snippets", "auth-jwt-hs256")
module("snippets", "auth-jwt-rs256")
module("snippets", "auth-ldap")
module("snippets", "auth-oauth-google")
module("snippets", "custom-plugin-legacy-api")
module("snippets", "custom-plugin")
module("snippets", "guice")
module("snippets", "gson")
module("snippets", "http2-push")
module("snippets", "http2-netty")
module("snippets", "http2-jetty")
module("snippets", "html-widget")
module("snippets", "html")
module("snippets", "jackson")
module("snippets", "client-json")
module("snippets", "locations")
module("snippets", "metrics")
module("snippets", "upload-file")
module("snippets", "upload-file-testing-config")
module("snippets", "download-file")
module("snippets", "post")
module("snippets", "post-form-parameters")
module("snippets", "session-cookie")
module("snippets", "sessions")
module("snippets", "static-content")
module("snippets", "timeout")
module("snippets", "autohead")
module("snippets", "autoreload-engine-main")
module("snippets", "autoreload-embedded-server")
module("snippets", "client-download-file")
module("snippets", "client-logging")
module("snippets", "embedded-server")
module("snippets", "embedded-server-modules")
module("snippets", "embedded-server-native")
module("snippets", "engine-main")
module("snippets", "engine-main-modules")
module("snippets", "freemarker")
module("snippets", "velocity")
module("snippets", "mustache")
module("snippets", "thymeleaf")
module("snippets", "client-upload-file")
module("snippets", "client-download-streaming")
module("snippets", "client-parallel-requests")
module("snippets", "client-timeout")
module("snippets", "client-retry")
module("snippets", "client-cookies")
module("snippets", "client-customize-default-validation")
module("snippets", "client-validate-response")
module("snippets", "simulate-slow-server")
module("snippets", "e2e")
module("snippets", "google-appengine-standard")
module("snippets", "client-auth-basic")
module("snippets", "client-auth-digest")
module("snippets", "client-auth-oauth-google")
module("snippets", "caching-headers")
module("snippets", "micrometer-metrics")
module("snippets", "pebble")
module("snippets", "auth-form-session")
module("snippets", "aws-elastic-beanstalk")
module("snippets", "conditional-headers")
module("snippets", "ssl-embedded-server")
module("snippets", "ssl-engine-main")
module("snippets", "server-websockets")
module("snippets", "client-websockets")
module("snippets", "client-testing-mock")
module("snippets", "json-kotlinx")
module("snippets", "client-json-kotlinx")
module("snippets", "logging")
module("snippets", "call-id")
module("snippets", "cors-frontend")
module("snippets", "cors-backend")
module("snippets", "compression")
module("snippets", "client-content-encoding")
module("snippets", "client-caching")
module("snippets", "client-default-request")
module("snippets", "client-http-send")
module("snippets", "fatjar")
module("snippets", "tutorial-http-api")
