[versions]
docker-compose = "0.17.21"
kotlin = "2.4.0"
logback = "1.6.3"
opentelemetry = "2.18.1-alpha"
opentelemetry_semconv = "1.34.0"
opentelemetry_exporter_otlp = "1.52.0"
opentelemetry_sdk_extension_autoconfigure = "1.52.0"

[libraries]
opentelemetry-sdk-extension-autoconfigure = { module = "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure", version.ref = "opentelemetry_sdk_extension_autoconfigure" }
opentelemetry-semconv = { module = "io.opentelemetry.semconv:opentelemetry-semconv", version.ref = "opentelemetry_semconv" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry_exporter_otlp" }
opentelemetry-ktor = { module = "io.opentelemetry.instrumentation:opentelemetry-ktor-3.0", version.ref = "opentelemetry" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
docker-compose = { id = "com.avast.gradle.docker-compose", version.ref = "docker-compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
