#!/usr/bin/env bash
#
# Air cloud environment startup for the Ktor documentation repository.
#
# What a task needs here:
#   * `/topics`, `/images`, `ktor.tree` etc. are plain Writerside sources - no tooling required.
#   * `/codeSnippets` is a Gradle project aggregating ~160 runnable Ktor samples, plus a
#     handful of standalone Gradle/npm projects under `codeSnippets/snippets/*`.
#     Those need a JDK per Gradle toolchain used by the samples (11, 17, 21) and a warm
#     Gradle dependency cache.
#
# The script is idempotent and runs in two modes (see AIR_STARTUP_MODE):
#   warmup - snapshot-baking run: install toolchains, prime every cache we can, then block
#            in `healthcheck` so the finished downloads/compiles land in the snapshot.
#   task   - real task run: only make sure the toolchain and configuration are in place and
#            return promptly; the caches come from the snapshot.
#
# No long-running server is left behind on purpose: nearly every sample binds port 8080,
# so a task must find that port free. `healthcheck` starts a sample server, proves it
# answers, and shuts it down again.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SNIPPETS_DIR="$REPO_ROOT/codeSnippets"
JDKS_DIR="$HOME/.jdks"
ENV_FILE="$HOME/.air/ktor-docs-env.sh"
ENV_MARKER="# >>> air ktor-documentation env >>>"
# JDK 21 runs Gradle itself; 17 and 11 are needed as Gradle toolchains, because
# codeSnippets/gradle.properties disables toolchain auto-provisioning.
PRIMARY_JDK_VERSION=21
JDK_VERSIONS="21 17 11"
SMOKE_MODULE="auth-basic"
SMOKE_PORT=8080

if [ "${AIR_STARTUP_MODE:-}" = "warmup" ]; then WARMUP=1; else WARMUP=; fi

log() { printf '[startup] %s %s\n' "$(date -u '+%H:%M:%S')" "$*"; }

# ---------------------------------------------------------------------------
# Outbound HTTP in this environment only works through the egress proxy, and the
# JVM does not pick up http_proxy/HTTPS_PROXY on its own. Derive host/port once.
# ---------------------------------------------------------------------------
PROXY_HOST=""
PROXY_PORT=""
detect_proxy() {
  local url="${HTTPS_PROXY:-${https_proxy:-${HTTP_PROXY:-${http_proxy:-}}}}"
  [ -n "$url" ] || { log "no egress proxy configured; using direct connections"; return 0; }
  local hostport="${url#*://}"
  hostport="${hostport%%/*}"
  PROXY_HOST="${hostport%%:*}"
  PROXY_PORT="${hostport##*:}"
  [ "$PROXY_PORT" = "$PROXY_HOST" ] && PROXY_PORT=80
  log "egress proxy: $PROXY_HOST:$PROXY_PORT"
}

java_tool_options() {
  [ -n "$PROXY_HOST" ] || return 0
  printf -- '-Dhttp.proxyHost=%s -Dhttp.proxyPort=%s -Dhttps.proxyHost=%s -Dhttps.proxyPort=%s -Dhttp.nonProxyHosts=localhost|127.0.0.1' \
    "$PROXY_HOST" "$PROXY_PORT" "$PROXY_HOST" "$PROXY_PORT"
}

# ---------------------------------------------------------------------------
# Toolchains
# ---------------------------------------------------------------------------
install_jdks() {
  mkdir -p "$JDKS_DIR"
  local v dest tmp dir
  for v in $JDK_VERSIONS; do
    dest="$JDKS_DIR/temurin-$v"
    if [ -x "$dest/bin/javac" ]; then
      log "JDK $v already installed at $dest"
      continue
    fi
    log "downloading Temurin JDK $v ..."
    tmp="$(mktemp -d)"
    if ! curl -fsSL --retry 3 -o "$tmp/jdk.tar.gz" \
         "https://api.adoptium.net/v3/binary/latest/$v/ga/linux/x64/jdk/hotspot/normal/eclipse"; then
      log "ERROR: failed to download JDK $v from api.adoptium.net"
      rm -rf "$tmp"
      return 1
    fi
    tar -xzf "$tmp/jdk.tar.gz" -C "$tmp" || { log "ERROR: cannot unpack JDK $v"; rm -rf "$tmp"; return 1; }
    dir="$(find "$tmp" -mindepth 1 -maxdepth 1 -type d | head -1)"
    rm -rf "$dest"
    mv "$dir" "$dest" || { log "ERROR: cannot install JDK $v"; rm -rf "$tmp"; return 1; }
    rm -rf "$tmp"
    log "JDK $v installed: $("$dest/bin/java" -version 2>&1 | head -1)"
  done
}

# ---------------------------------------------------------------------------
# Shell environment. The launch runs this file as a child process, so exports made
# here die with it - persist them in a file and source it from the login/interactive
# shell profiles the agent and terminals actually read.
# ---------------------------------------------------------------------------
write_env_file() {
  mkdir -p "$(dirname "$ENV_FILE")"
  {
    echo "# Generated by .air/cloud/startup.sh - do not edit by hand."
    echo "export JAVA_HOME=\"$JDKS_DIR/temurin-$PRIMARY_JDK_VERSION\""
    echo 'export PATH="$JAVA_HOME/bin:$PATH"'
    echo "export JAVA_${PRIMARY_JDK_VERSION}_HOME=\"$JDKS_DIR/temurin-$PRIMARY_JDK_VERSION\""
    echo "export JAVA_17_HOME=\"$JDKS_DIR/temurin-17\""
    echo "export JAVA_11_HOME=\"$JDKS_DIR/temurin-11\""
    if [ -n "$PROXY_HOST" ]; then
      echo "# The JVM needs the egress proxy passed as system properties."
      echo "export JAVA_TOOL_OPTIONS=\"$(java_tool_options)\""
    fi
  } > "$ENV_FILE"
  log "wrote $ENV_FILE"
}

hook_login_shell() {
  local line=". \"$ENV_FILE\""
  local profile=""
  local f
  for f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
    if [ -f "$f" ]; then profile="$f"; break; fi
  done
  if [ -z "$profile" ]; then
    profile="$HOME/.profile"
    touch "$profile"
  fi
  for f in "$profile" "$HOME/.bashrc"; do
    [ -e "$f" ] || touch "$f"
    if ! grep -qF "$ENV_MARKER" "$f"; then
      {
        echo ""
        echo "$ENV_MARKER"
        echo "[ -f \"$ENV_FILE\" ] && $line"
        echo "# <<< air ktor-documentation env <<<"
      } >> "$f"
      log "hooked env file into $f"
    fi
  done
}

write_gradle_properties() {
  mkdir -p "$HOME/.gradle"
  {
    echo "# Generated by .air/cloud/startup.sh - do not edit by hand."
    echo "# codeSnippets/gradle.properties disables toolchain auto-download, so point"
    echo "# Gradle at the JDKs installed above."
    echo "org.gradle.java.installations.paths=$JDKS_DIR/temurin-21,$JDKS_DIR/temurin-17,$JDKS_DIR/temurin-11"
    echo "org.gradle.java.installations.auto-detect=true"
    if [ -n "$PROXY_HOST" ]; then
      echo "systemProp.http.proxyHost=$PROXY_HOST"
      echo "systemProp.http.proxyPort=$PROXY_PORT"
      echo "systemProp.https.proxyHost=$PROXY_HOST"
      echo "systemProp.https.proxyPort=$PROXY_PORT"
      echo 'systemProp.http.nonProxyHosts=localhost|127.0.0.1'
    fi
  } > "$HOME/.gradle/gradle.properties"
  log "wrote $HOME/.gradle/gradle.properties"
}

# A few samples (openapi-spec-gen-maven, tutorial-server-get-started-maven) build with
# Maven, which reads its proxy from settings.xml. Never clobber a user-provided file.
write_maven_settings() {
  [ -n "$PROXY_HOST" ] || return 0
  mkdir -p "$HOME/.m2"
  [ -e "$HOME/.m2/settings.xml" ] && return 0
  cat > "$HOME/.m2/settings.xml" <<XML
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
  <!-- Generated by .air/cloud/startup.sh -->
  <proxies>
    <proxy>
      <id>air-egress-http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>$PROXY_HOST</host>
      <port>$PROXY_PORT</port>
      <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
    </proxy>
    <proxy>
      <id>air-egress-https</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>$PROXY_HOST</host>
      <port>$PROXY_PORT</port>
      <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
XML
  log "wrote $HOME/.m2/settings.xml"
}

# ---------------------------------------------------------------------------
# Cache priming (warmup only - the results are what the snapshot is made of)
# ---------------------------------------------------------------------------

# Gradle wrapper distributions differ per standalone sample; pick a JDK the wrapper
# supports (Gradle 7.x cannot run on JDK 21).
jdk_for_wrapper() {
  local props="$1/gradle/wrapper/gradle-wrapper.properties"
  local major=""
  [ -f "$props" ] && major="$(sed -nE 's/.*gradle-([0-9]+)\..*/\1/p' "$props" | head -1)"
  if [ -n "$major" ] && [ "$major" -lt 8 ] 2>/dev/null; then
    echo "$JDKS_DIR/temurin-17"
  else
    echo "$JDKS_DIR/temurin-$PRIMARY_JDK_VERSION"
  fi
}

prime_main_build() {
  log "priming the aggregate codeSnippets build ..."
  ( cd "$SNIPPETS_DIR" && sh ./gradlew --version --console=plain ) || {
    log "ERROR: could not install the Gradle distribution for codeSnippets"
    return 1
  }
  # Configuring every sample downloads all build plugins; compiling downloads the
  # dependency graph and fills the build caches. --continue so that a single broken
  # sample does not stop the priming - `healthcheck` is what decides pass/fail.
  ( cd "$SNIPPETS_DIR" && sh ./gradlew testClasses --continue --console=plain > /tmp/air-prime-codesnippets.log 2>&1 )
  local rc=$?
  log "aggregate build priming finished (exit=$rc): $(grep -cE '^> Task .*FAILED' /tmp/air-prime-codesnippets.log) failed task(s), log: /tmp/air-prime-codesnippets.log"
  if [ $rc -ne 0 ]; then
    grep -A5 '^\* What went wrong' /tmp/air-prime-codesnippets.log | head -40
  fi
  return 0
}

prime_standalone_projects() {
  # Samples that are standalone Gradle builds (own wrapper/settings) rather than
  # modules of codeSnippets/settings.gradle.kts. Best effort: some of them target
  # Android/Kotlin Multiplatform or are pinned to older Gradle versions.
  local dir name jdk rc
  for dir in "$SNIPPETS_DIR"/snippets/*/; do
    [ -f "$dir/gradlew" ] || continue
    name="$(basename "$dir")"
    jdk="$(jdk_for_wrapper "$dir")"
    log "priming standalone sample $name (JAVA_HOME=$(basename "$jdk")) ..."
    ( cd "$dir" && JAVA_HOME="$jdk" PATH="$jdk/bin:$PATH" sh ./gradlew testClasses --console=plain \
        > "/tmp/air-prime-$name.log" 2>&1 )
    rc=$?
    [ $rc -eq 0 ] && log "  $name primed" || log "  $name not primed (exit=$rc, see /tmp/air-prime-$name.log) - continuing"
  done
}

prime_node_projects() {
  local dir name
  for dir in "$SNIPPETS_DIR"/snippets/*/; do
    [ -f "$dir/package.json" ] || continue
    name="$(basename "$dir")"
    log "priming npm dependencies for $name ..."
    if [ -f "$dir/package-lock.json" ]; then
      ( cd "$dir" && npm ci > "/tmp/air-prime-npm-$name.log" 2>&1 ) \
        || log "  npm ci failed for $name (see /tmp/air-prime-npm-$name.log) - continuing"
    else
      ( cd "$dir" && npm install > "/tmp/air-prime-npm-$name.log" 2>&1 ) \
        || log "  npm install failed for $name (see /tmp/air-prime-npm-$name.log) - continuing"
    fi
  done
}

# ---------------------------------------------------------------------------
# healthcheck - proves the environment does what a task needs, not just that the
# installs finished: Gradle runs on the expected JDK, the toolchains the samples
# declare resolve, a sample compiles and passes its test, and the sample server it
# documents actually serves over HTTP.
# ---------------------------------------------------------------------------
# `ss`/`netstat` are not guaranteed to exist in the image, so probe the port with curl:
# exit code 7 means "connection refused", i.e. nothing is listening.
port_in_use() {
  curl -sS --noproxy '*' --max-time 3 -o /dev/null "http://127.0.0.1:$SMOKE_PORT/" 2>/dev/null
  [ $? -ne 7 ]
}

healthcheck() {
  local rc

  log "healthcheck: java -version"
  "$JAVA_HOME/bin/java" -version || { log "healthcheck FAILED: JDK $PRIMARY_JDK_VERSION is not usable"; return 1; }

  # Compiles against the Gradle toolchains the samples declare: auth-basic (default JVM,
  # 21) and compression (jvmToolchain(11)). A missing toolchain fails here.
  log "healthcheck: building :$SMOKE_MODULE and :compression (toolchain 11) ..."
  ( cd "$SNIPPETS_DIR" && sh ./gradlew ":$SMOKE_MODULE:build" ":compression:classes" --console=plain ) || {
    log "healthcheck FAILED: Gradle could not build the sample modules"
    return 1
  }

  if port_in_use; then
    log "healthcheck FAILED: port $SMOKE_PORT is already in use"
    return 1
  fi

  log "healthcheck: starting the :$SMOKE_MODULE Ktor server on port $SMOKE_PORT ..."
  ( cd "$SNIPPETS_DIR" && sh ./gradlew ":$SMOKE_MODULE:run" --console=plain ) > /tmp/air-smoke-server.log 2>&1 &
  local server_pid=$!

  local body="" waited=0
  while :; do
    if ! kill -0 "$server_pid" 2>/dev/null; then
      log "healthcheck FAILED: the sample server exited before answering; last output:"
      tail -30 /tmp/air-smoke-server.log
      return 1
    fi
    body="$(curl -sS --noproxy '*' --max-time 5 -u jetbrains:foobar "http://127.0.0.1:$SMOKE_PORT/" 2>/dev/null)"
    if [ "$body" = "Hello, jetbrains!" ]; then
      log "healthcheck: server answered authenticated GET / with the expected body"
      break
    fi
    waited=$((waited + 3))
    log "healthcheck: waiting for http://127.0.0.1:$SMOKE_PORT/ (${waited}s elapsed) ..."
    sleep 3
  done

  # The sample's whole point is Basic auth, so assert the unauthenticated path too.
  local code
  code="$(curl -sS --noproxy '*' --max-time 5 -o /dev/null -w '%{http_code}' "http://127.0.0.1:$SMOKE_PORT/")"
  rc=0
  if [ "$code" != "401" ]; then
    log "healthcheck FAILED: expected HTTP 401 without credentials, got $code"
    rc=1
  else
    log "healthcheck: anonymous GET / correctly returned 401"
  fi

  log "healthcheck: stopping the sample server (port $SMOKE_PORT must stay free for tasks)"
  pkill -P "$server_pid" 2>/dev/null
  kill "$server_pid" 2>/dev/null
  wait "$server_pid" 2>/dev/null
  # `gradle run` forks the application into its own JVM, which outlives the launcher.
  pkill -f 'io[.]ktor[.]server[.]netty[.]EngineMain' 2>/dev/null
  while port_in_use; do
    log "healthcheck: waiting for port $SMOKE_PORT to be released ..."
    pkill -f 'io[.]ktor[.]server[.]netty[.]EngineMain' 2>/dev/null
    sleep 2
  done
  log "healthcheck: port $SMOKE_PORT released"

  [ $rc -eq 0 ] && log "healthcheck: PASSED"
  return $rc
}

# ---------------------------------------------------------------------------
main() {
  log "starting (mode=${AIR_STARTUP_MODE:-task}, repo=$REPO_ROOT)"
  detect_proxy
  install_jdks || exit 1
  write_env_file
  hook_login_shell
  write_gradle_properties
  write_maven_settings

  # shellcheck disable=SC1090
  . "$ENV_FILE"

  if [ -n "$WARMUP" ]; then
    prime_main_build || exit 1
    prime_standalone_projects
    prime_node_projects
    healthcheck || { log "startup FAILED"; exit 1; }
  else
    # Keep a task boot short: the snapshot already carries the Gradle distribution,
    # caches and compiled output. Just make sure the wrapper is usable.
    ( cd "$SNIPPETS_DIR" && sh ./gradlew --version --console=plain > /tmp/air-gradle-version.log 2>&1 ) \
      || { log "ERROR: Gradle wrapper is not usable, see /tmp/air-gradle-version.log"; exit 1; }
    log "Gradle wrapper ready ($(grep -m1 '^Gradle ' /tmp/air-gradle-version.log))"
  fi

  log "done"
}

main "$@"
