GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2p3dC1wcm92aWRlci1kb21haW4vIiwiYXVkIjoiand0LWF1ZGllbmNlIiwic3ViIjoiamV0YnJhaW5zIn0.ZT5cX_2XHn_nrhhghfeP_cABSifYZrEtzoKKtQiwCN0
