GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InB1YmxpYzpjNDI0YjY3Yi1mZTI4LTQ1ZDctYjAxNS1mNzlkYTUwYjViMjEiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJqd3QtYXVkaWVuY2UiLCJjbGllbnRfaWQiOiJqZXRicmFpbnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwLyIsImp0aSI6IjQ1NzM4MmQyLTg0NGMtNDM4OS05YWI4LWRmOWRmMjM4ZTdmOSIsInN1YiI6ImpldGJyYWlucyJ9.B9F2_O9u_J3uoHu6GnZ7FRbq4i68t7P1LRJXse21wm_0QrZ7rganYS_MxFEl8DIoywaIMoA6UveOge8T_az19dVBv3A--EvcKGFy_89XFQVuLe0DnCM2-ZFbtu1H2KCM0aSok2Yn3ktF0auHw8LHXZ17DelznXlgExZwQzTvug-7J3ITHBJhKDkkF5e06dH4xyUbUBW6mmoAqljmuFm238zmN5y5Pp3yWDueWri_MkZog5E0lyGXkJr5LOzFupCPkwVJTVSP4-oTrfD-NCOjdCxiv-6sfdK-h6nJwYfKOTBSHfC0c5DaoWgajdGyoQ0gpNlv2prZeGfsfURkstsKjg