ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.DIKt.configureDependencyInjection
      - com.example.SerializationKt.configureSerialization
      - com.example.ExposedKt.configureExposed
      - com.example.StatusPagesKt.configureStatusPages
      - com.example.RoutingKt.configureRouting
