POST http://localhost:8080/text
Content-Type: text/plain

Hello, world!

###

POST http://localhost:8080/bytes
Content-Type: text/plain

Hello, world!

###

POST http://localhost:8080/channel
Content-Type: text/plain

Hello, world!

###

POST http://localhost:8080/upload
Content-Type: application/octet-stream

< ./ktor_logo.png