services:
  ldap_server:
    build: .
    environment:
      LDAP_ADMIN_PASSWORD: foobarbaz
      LDAP_BASE_DN: dc=ktor,dc=io
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: osixia/phpldapadmin
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config: