GET http://0.0.0.0:8080/tasks/byPriority/Medium
    Accept: application/json

###

POST http://0.0.0.0:8080/tasks
Content-Type: application/json

{
    "name": "cooking",
    "description": "Cook the dinner",
    "priority": "High"
}

###

DELETE http://0.0.0.0:8080/tasks/gardening