POST http://localhost:8080/text
Content-Type: text/plain

Some text

###
POST http://0.0.0.0:8080/json
Content-Type: application/json

{
  "id": -1,
  "firstName" : "Jet",
  "lastName": "Brains"
}

###
POST http://localhost:8080/array
Content-Type: text/plain

-1